name: flutter_atoms
description: Some best practice and ready to go solutions for flutter projects
version: 1.3.0
homepage: https://github.com/JetRabbits/flutter_atoms
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  persist_theme:
    git:
      url: https://github.com/JetRabbits/persist_theme.git
  local_auth:
  uuid:
  package_info_plus:
  device_info_plus:
  android_id:
  flutter_draft:
    git:
      url: https://github.com/JetRabbits/flutter_draft.git
  equatable:
  cached_network_image:
  shared_preferences:
  flutter_cache_manager:
  story_view: ^0.14.0
  json_serializable:
  auto_size_text:
  url_launcher:
  flutter_whatsnew:
    git:
      url: https://github.com/JetRabbits/flutter_whatsnew.git
  collection:
  encrypted_shared_preferences: ^3.0.1
  intl:
  logging:
  get_it:
  injectable:
  share_plus:
  archive:
  flutter_keyboard_visibility:
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  injectable_generator:
  build_runner:
flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
  class_name: AtomsStrings

