name: flutter_atoms
description: Some best practice and ready to go solutions for flutter projects
version: 1.0.7
homepage: https://github.com/JetRabbits/flutter_atoms
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  persist_theme: ^1.7.0
  local_auth:
  uuid:
  package_info_plus:
  device_info_plus:
  flutter_draft:
    git:
      url: https://gitlab.jetrabbits.com/jetrabbits_product/flutter_draft.git
  equatable:
  cached_network_image:
  flutter_secure_storage:
  shared_preferences:
  flutter_cache_manager:
  story_view: ^0.13.2
  json_serializable:
  auto_size_text:
  url_launcher:
  flutter_whatsnew: ^1.0.3
  collection:
  crypted_preferences:
  intl:
  logging:
  get_it:
  injectable:
  share:
  archive:
  flutter_keyboard_visibility:
dependency_overrides:
  provider: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  mocktail:
  injectable_generator:
  build_runner:
flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
  class_name: AtomsStrings

