name: flutter_atoms
description: Some best practice and ready to go solutions for flutter projects
version: 1.0.4
author: JetRabbits
homepage: https://github.com/JetRabbits/flutter_atoms
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  persist_theme:
  get_version:
    git: https://github.com/Creky/get_version.git
  flutter_draft:
    git:
      url: https://gitlab.jetrabbits.com/jetrabbits_product/flutter_draft.git
  equatable:
  cached_network_image:
  flutter_secure_storage:
  shared_preferences:
  flutter_cache_manager:
  story_view: ^0.13.0
  json_serializable:
  auto_size_text:
  url_launcher:
  flutter_whatsnew:
  collection:
  crypted_preferences:
  intl:
  logging:
  get_it:
  injectable:
dependency_overrides:
  flutter_cache_manager: ^3.1.2
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  plugin_platform_interface: ^2.0.1
  flutter_markdown: ^0.6.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  mocktail:
  injectable_generator:
  build_runner:
flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
  class_name: AtomsStrings

