name: flutter_atoms
description: Some best practice and ready to go solutions for flutter projects
version: 0.0.3
author: JetRabbits
homepage: https://github.com/JetRabbits/flutter_atoms
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  persist_theme: ^1.7.0
  get_version:
    git: https://github.com/Creky/get_version.git
  equatable: ^2.0.0
  cached_network_image: ^3.0.0
  flutter_secure_storage: ^4.2.0
  shared_preferences: ^2.0.6
  flutter_cache_manager: ^3.1.1
  story_view: ^0.13.1
  json_serializable: ^4.1.3
  auto_size_text: ^2.1.0
  url_launcher: ^6.0.4
  flutter_whatsnew: ^1.0.3
  collection: ^1.15.0
  crypted_preferences: ^0.0.2
  intl: ^0.17.0
  logging: ^1.0.1
  get_it: ^7.1.3
  injectable: ^1.4.1
dependency_overrides:
  flutter_cache_manager: ^3.1.1
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  plugin_platform_interface: ^2.0.0
  flutter_markdown: ^0.6.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.5
  mocktail: ^0.1.2
  injectable_generator:
  build_runner:
flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
  class_name: AtomsStrings

